# Generated by Django 4.2.20 on 2025-04-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('prix', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('double', 'Double'), ('suite', 'Suite'), ('deluxe', 'Deluxe')], max_length=100)),
                ('etat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.CharField(max_length=100)),
                ('date_fin', models.CharField(max_length=100)),
                ('prix_total', models.CharField(max_length=100)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_aPayer', models.CharField(max_length=100)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
