# Generated by Django 4.2.20 on 2025-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='chambre',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='prix_aPayer',
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Payé', 'Payé')], default='En attente', max_length=20),
        ),
    ]
