# Generated by Django 4.2.20 on 2025-05-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='image',
            field=models.ImageField(default='', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
